---
title: "R Notebook"
output: html_notebook
---

```{r load_packages,warning=F,message=F}
# LOAD LIBRARIES
library(tidyverse) 
library(Seurat) 
library(patchwork) 
library(ggplot2)
library(dplyr)
```


```{r load_data,warning=F,message=F}
# Load data
untar("/Users/chiara/Downloads/GSE224411_RAW.tar",
      exdir = "/Users/chiara/Downloads/GSE224411_RAW")
list.files("/Users/chiara/Downloads/GSE224411_RAW")
```


```{r}
# PanIN
untar("/Users/chiara/Downloads/GSE224411_RAW/GSM7021871_PanIN.tar.gz",
  exdir = "/Users/chiara/Downloads/GSE224411_RAW/GSM7021871_PanIN")
#list.files("/Users/chiara/Downloads/GSE224411_RAW/GSM7021871_PanIN")
#list.files("/Users/chiara/Downloads/GSE224411_RAW/GSM7021871_PanIN/PanIN")
#list.files("/Users/chiara/Downloads/GSE224411_RAW/GSM7021871_PanIN/PanIN/analysis")
#list.files("/Users/chiara/Downloads/GSE224411_RAW/GSM7021871_PanIN/PanIN/analysis/clustering")
#list.files("/Users/chiara/Downloads/GSE224411_RAW/GSM7021871_PanIN/PanIN/analysis/clustering/1152735_analysis__clustering_graphclust_clusters.csv",sep = ",")
#analysis/clustering/graphclust/clusters.csv", sep = ","
```
```{r}
PanIN_data <- Load10X_Spatial(data.dir = "PanIN/")

## PUBLISHED DATA

original_labels <- read.delim("PanIN/analysis/clustering/1152735_analysis__clustering_graphclust_clusters.csv", sep = ",")

colnames(original_labels) <- c("orig.ident", "original_cluster")

PanIN_data <- AddMetaData(PanIN_data, metadata = original_labels)

# MT
PanIN_data[["percent.mt"]] <- PercentageFeatureSet(
  PanIN_data,
  pattern = "^MT-")

# VISUALIZATION 
p0 <- SpatialFeaturePlot(PanIN_data, 
                         features = c("nFeature_Spatial", "nCount_Spatial"),
                         image.alpha = .5,
                         pt.size.factor = 3) + 
   theme(legend.position = "right")
p0


p2<- VlnPlot(
  PanIN_data,
  features = c("nFeature_Spatial", "nCount_Spatial","percent.mt"),
  ncol = 3,
  pt.size = 0.1) + NoLegend()
p2

#FILTERING
PanIN_data <- subset(PanIN_data, 
                   subset = nFeature_Spatial > 1000
                   & nFeature_Spatial < 7500
                   & percent.mt < 5)

SpatialFeaturePlot(PanIN_data, 
                         features = c("nFeature_Spatial", "nCount_Spatial"),
                         image.alpha = .5,
                         pt.size.factor = 3) + 
   theme(legend.position = "right")

## NORMALIZATION
PanIN_data <- SCTransform(PanIN_data, assay = "Spatial", verbose = FALSE)
PanIN_data

## REDUCTION AND CLUSTERING

PanIN_data <- RunPCA(PanIN_data, assay = "SCT", verbose = FALSE)
p3<- DimPlot(PanIN_data, reduction = "pca", label = TRUE)
p3
p4<- ElbowPlot(PanIN_data)
p4

PanIN_data <- FindNeighbors(PanIN_data, reduction = "pca", dims = 1:20)

#for (res in c(0.1, 0.2, 0.4, 0.6)) {
#  PanIN_data <- FindClusters(PanIN_data, resolution = res)
#  print(DimPlot(PanIN_data, label = TRUE) + ggtitle(paste("Resolution", res)))}

PanIN_data <- FindClusters(PanIN_data, verbose = FALSE,resolution = 0.3)

PanIN_data <- RunUMAP(PanIN_data, reduction = "pca", dims = 1:20)
p5<- DimPlot(PanIN_data, reduction = "umap", label = TRUE, pt.size = 1)
p5

p6 <- SpatialDimPlot(PanIN_data, 
                     label = TRUE, 
                     label.size = 3, 
                     image.alpha = .5,
                     pt.size.factor = 3) +
      theme(legend.position = "none")
p6

SpatialDimPlot(PanIN_data, group.by = "seurat_clusters",pt.size.factor = 3)
SpatialDimPlot(PanIN_data, group.by = "original_cluster",pt.size.factor = 3)
SpatialDimPlot(PanIN_data, 
               group.by = "seurat_clusters",
                     label = TRUE, 
                     label.size = 3, 
                     image.alpha = .5,
               pt.size.factor = 4) +
      theme(legend.position = "right")
SpatialDimPlot(PanIN_data,
               group.by = "original_cluster",
                     label = TRUE, 
                     label.size = 3, 
                     image.alpha = .5,
               pt.size.factor = 4) +
      theme(legend.position = "right")

#highlight of some clusters
p7 <- SpatialDimPlot(PanIN_data, 
                     cells.highlight = CellsByIdentities(
                       object = PanIN_data, idents = c(0, 2)), 
                     facet.highlight = TRUE, 
                     ncol = 2,
                     cols.highlight = c("forestgreen","firebrick"),
                     pt.size.factor = 4)+ 
  theme(legend.position = "right")
p7



## COMPARE CLUSTERS
de_markers <- FindMarkers(PanIN_data, ident.1 = 0, ident.2 = 1)
de_markers <- de_markers|>arrange(desc(avg_log2FC))
de_markers %>%
  slice_max(order_by = avg_log2FC, n = 7)


# FIND ALL MARKERS
all_markers_PanIN <- FindAllMarkers(
  PanIN_data,
  only.pos = TRUE,
  min.pct = 0.25,
  logfc.threshold = 0.25)

top10_PanIN <- all_markers_PanIN %>%
  group_by(cluster) %>%
  slice_max(order_by = avg_log2FC, n = 3)
head(top10_PanIN)

p8<- DoHeatmap(
  PanIN_data,
  features = top10_PanIN$gene)
p8 


#ANNOTATION
new.ids <- c(
  "fibroblasts/CAFs",
  "immune cells",
  "acinar cells",
  "ductal cells",
  "endocrine cells",
  "fibroblasts/CAFs",
  "ductal cells",
  "stellate cells")

names(new.ids) <- levels(PanIN_data)

PanIN_data <- RenameIdents(PanIN_data, new.ids)

PanIN_data$annotation <- Idents(PanIN_data)

DimPlot(
  PanIN_data,
  reduction = "umap",
  label = TRUE,
)

SpatialDimPlot(
  PanIN_data,
  group.by = "annotation",
  label = FALSE,
  pt.size.factor = 4
)

saveRDS(PanIN_data, file = "PanIN_data.rds")
```


